version:"3"
services:
  miniaspire:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 80
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - miniaspire_pg
    environment:
      DEBUG: 'true'
    networks:
      testing_net:
        ipv4_address: 162.28.1.1

  miniaspire_pg:
    image: postgres:latest
    ports:
      - 6434:5432
    volumes:
      - db_data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: miniaspire
    networks:
      testing_net:
        ipv4_address: 162.28.1.2

  miniaspire_pg_testing:
    image: postgres:latest
    ports:
      - 6435:5432
    volumes:
      - db_data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: miniaspire
    networks:
      testing_net:
        ipv4_address: 162.28.1.4

volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 162.28.0.0/16
